<?xml version="1.0"?>
<package format="3">
  <name>kinematic_kitchen_interfaces</name>
  <version>0.1.0</version>
  <description>ROS 2 interfaces for Kinematic Kitchen.</description>
  <maintainer email="15.oscar.amo@gmail.com">amo-grau</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <!-- Without this, catkin_pkg defaults the build type to "catkin" and colcon
       builds the package with ROS 1 conventions. -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
